// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8LRWEYU40RGAsAOLwwmyq-v8ByCSHNI',
    appId: '1:804482111917:web:9021f1be705bb1b3d02924',
    messagingSenderId: '804482111917',
    projectId: 'chatapp-8fc09',
    authDomain: 'chatapp-8fc09.firebaseapp.com',
    storageBucket: 'chatapp-8fc09.appspot.com',
    measurementId: 'G-K466QYRH53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3c4PeCuZAGt1kazEe1iqUNx3qmn-Low',
    appId: '1:804482111917:android:0e8ddb1ad2f11011d02924',
    messagingSenderId: '804482111917',
    projectId: 'chatapp-8fc09',
    storageBucket: 'chatapp-8fc09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCys6cnt2fKWDkxdWDSmhWb8lxiaCFlWBI',
    appId: '1:804482111917:ios:d2aca008b238771ed02924',
    messagingSenderId: '804482111917',
    projectId: 'chatapp-8fc09',
    storageBucket: 'chatapp-8fc09.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
